---
vmDefaults:
  cloudInitSecret: secret/data/hub/cloud-init
  accessMode: "ReadWriteMany"
  storageClassName: "ocs-storagecluster-ceph-rbd-virtualization"
  volumeMode: "Block"
  count: 1
  flavor: medium
  workload: server
  os: rhel9
  storage: 30Gi
  memory: 4Gi
  machineType: pc-q35-rhel8.4.0
  cores: 1
  sockets: 1
  threads: 1
  template: rhel9-server-medium
  sshsecret: secret/data/hub/vm-ssh
  cloudinitsecret: secret/data/hub/cloud-init
  sshpubkeyfield: publickey
  # extraLabels is available for default extra labels to add to the virtualmachine
  # extraAnnotations is available for default extra labels to add to the virtualmachine
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22

vms:
  kiosk: {}
  edgenode:
    count: 4
    role: edgenode
  edgerelay:
    count: 2
    role: edgerelay
    memory: 8Gi
    cores: 4
    sockets: 1
    threads: 2
  visualizer:
    count: 1
    role: visualizer
    memory: 16Gi
    cores: 8
    sockets: 1
    threads: 2
