{{- if .Values.awsCreds.inject }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: aws-creds
  namespace: ansible-automation-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: aws-creds
  dataFrom:
  - extract:
      key: {{ .Values.awsCreds.key }}
{{- end }}
