#!/usr/bin/env ansible-playbook
---
- name: Configure this pattern's AAP Controller
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    ansible_host: ""
    admin_password: ""
    secrets: ""
    controller_configuration_dir: /tmp/controller_configuration_dir
  tasks:
    - name: Determine which repo to clone
      kubernetes.core.k8s_info:
        name: aap-configascode-cm
        namespace: ansible-automation-platform
        kind: ConfigMap
      register: repo_config

    - name: Assign variables
      ansible.builtin.set_fact:
        controller_hostname: "{{ ansible_host }}"
        controller_username: admin
        controller_password: "{{ admin_password }}"
        controller_validate_certs: false

    - name: Checkout infrastructure-as-code repository
      ansible.builtin.git:
        repo: "{{ repo_config.resources[0].data.aap_configascode_repo }}"
        version: "{{ repo_config.resources[0].data.aap_configascode_revision }}"
        dest: "{{ controller_configuration_dir }}"
        clone: true
        update: true
        recursive: true

    - name: Include vars from infrastructure-as-code repository
      ansible.builtin.include_vars:
        dir: "{{ controller_configuration_dir }}"
        ignore_unknown_extensions: true
        extensions:
          - json
          - yaml
          - yml

    - name: Configure AAP Controller
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
